# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO

# pnpm workspace configuration
# See: https://pnpm.io/workspaces

packages:
  # Shared packages (Node-owned, pure libraries)
  - "packages/*"
  # Operator services (future: git-review-daemon, git-admin-daemon)
  - "services/*"
