// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@cogni/ai-tools/tools/poly-close-position`
 * Purpose: AI tool that closes an open Polymarket position via a SELL order through PolyTradeCapability. Routes to `bundle.closePosition` which is the only legal SELL path for agents.
 * Scope: Tool contract + factory + stub. Pure package. Does not read env vars or import adapters.
 * Invariants:
 *   - TOOL_ID_NAMESPACED: id is `core__poly_close_position`
 *   - EFFECT_TYPED: effect is `external_side_effect` — real money moves on success
 *   - CLOSE_POSITION_IS_SELL_ONLY: this tool exclusively issues SELL orders
 *   - CAPABILITY_NOT_ADAPTER: routes through `PolyTradeCapability.closePosition`
 * Side-effects: none
 * Links: work/items/task.0323.md
 * @public
 */

import { z } from "zod";

import type { BoundTool, ToolContract, ToolImplementation } from "../types";
import type {
  PolyClosePositionRequest,
  PolyPlaceTradeReceipt,
  PolyTradeCapability,
} from "./poly-place-trade";

// ─────────────────────────────────────────────────────────────────────────────
// Input / output schemas
// ─────────────────────────────────────────────────────────────────────────────

export const PolyClosePositionInputSchema = z.object({
  tokenId: z
    .string()
    .min(1)
    .describe(
      "ERC-1155 asset id (decimal string) of the outcome token to sell. " +
        "Must match an existing open position on the operator EOA."
    ),
  max_size_usdc: z
    .number()
    .positive()
    .max(25)
    .describe(
      "Notional USDC cap for the close. Actual size = min(cap, position market value). " +
        "Use the current position value to close fully, or less to partially exit."
    ),
  limit_price: z
    .number()
    .gt(0)
    .lt(1)
    .optional()
    .describe(
      "Limit price for the SELL, strictly between 0 and 1. " +
        "Omit to use aggressive take-bid pricing (best_bid - small buffer)."
    ),
});
export type PolyClosePositionInput = z.infer<
  typeof PolyClosePositionInputSchema
>;

export const PolyClosePositionOutputSchema = z.object({
  order_id: z
    .string()
    .min(1)
    .describe("Platform-assigned CLOB order id (0x-prefixed hex)."),
  client_order_id: z
    .string()
    .min(1)
    .describe("Echoes the idempotency key generated by the capability."),
  status: z
    .enum(["pending", "open", "filled", "partial", "canceled", "error"])
    .describe(
      "Canonical status. 'open' = resting; 'filled' = fully matched; 'error' = rejected."
    ),
  filled_size_usdc: z
    .number()
    .min(0)
    .describe("Cumulative filled notional in USDC at receipt time."),
  submitted_at: z.string().describe("ISO-8601 timestamp."),
  profile_url: z
    .string()
    .url()
    .describe(
      "Polymarket profile URL for the Cogni operator wallet — share with the user to view updated positions."
    ),
});
export type PolyClosePositionOutput = z.infer<
  typeof PolyClosePositionOutputSchema
>;

export type PolyClosePositionRedacted = PolyClosePositionOutput;

// ─────────────────────────────────────────────────────────────────────────────
// Contract
// ─────────────────────────────────────────────────────────────────────────────

export const POLY_CLOSE_POSITION_NAME = "core__poly_close_position" as const;

export const polyClosePositionContract: ToolContract<
  typeof POLY_CLOSE_POSITION_NAME,
  PolyClosePositionInput,
  PolyClosePositionOutput,
  PolyClosePositionRedacted
> = {
  name: POLY_CLOSE_POSITION_NAME,
  description:
    "Close (SELL) an open Polymarket position through the Cogni operator wallet. " +
    "Input: tokenId (ERC-1155 asset) + max_size_usdc cap + optional limit_price. " +
    "Actual size is min(cap, current position market value). " +
    "Returns the real CLOB order_id + a Polymarket profile URL. " +
    "This spends real USDC — only call when the user has explicitly asked to exit a position.",
  effect: "external_side_effect",
  inputSchema: PolyClosePositionInputSchema,
  outputSchema: PolyClosePositionOutputSchema,
  redact: (output: PolyClosePositionOutput): PolyClosePositionRedacted =>
    output,
  allowlist: [
    "order_id",
    "client_order_id",
    "status",
    "filled_size_usdc",
    "submitted_at",
    "profile_url",
  ] as const,
};

// ─────────────────────────────────────────────────────────────────────────────
// Implementation factory (capability-injected)
// ─────────────────────────────────────────────────────────────────────────────

export interface PolyClosePositionDeps {
  polyTradeCapability: PolyTradeCapability;
}

export function createPolyClosePositionImplementation(
  deps: PolyClosePositionDeps
): ToolImplementation<PolyClosePositionInput, PolyClosePositionOutput> {
  return {
    execute: async (
      input: PolyClosePositionInput
    ): Promise<PolyClosePositionOutput> => {
      const request: PolyClosePositionRequest = {
        tokenId: input.tokenId,
        max_size_usdc: input.max_size_usdc,
        ...(input.limit_price !== undefined
          ? { limit_price: input.limit_price }
          : {}),
      };
      const receipt: PolyPlaceTradeReceipt =
        await deps.polyTradeCapability.closePosition(request);
      return {
        order_id: receipt.order_id,
        client_order_id: receipt.client_order_id,
        status: receipt.status,
        filled_size_usdc: receipt.filled_size_usdc,
        submitted_at: receipt.submitted_at,
        profile_url: receipt.profile_url,
      };
    },
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Stub (catalog registration — replaced at runtime by the real impl)
// ─────────────────────────────────────────────────────────────────────────────

export const polyClosePositionStubImplementation: ToolImplementation<
  PolyClosePositionInput,
  PolyClosePositionOutput
> = {
  execute: async (): Promise<PolyClosePositionOutput> => {
    throw new Error(
      "core__poly_close_position stub invoked — container did not inject PolyTradeCapability. " +
        "Verify POLY_CLOB_* + POLY_PROTO_* are configured on this pod."
    );
  },
};

export const polyClosePositionBoundTool: BoundTool<
  typeof POLY_CLOSE_POSITION_NAME,
  PolyClosePositionInput,
  PolyClosePositionOutput,
  PolyClosePositionRedacted
> = {
  contract: polyClosePositionContract,
  implementation: polyClosePositionStubImplementation,
};
