apiVersion: ENC[AES256_GCM,data:Nyk=,iv:yGa0lKOWk4SfyvY/ydCOtq1DNqbeBAx+zbjrHqDu6Ng=,tag:Zm7j6lcHn00UYIlYD9ykIA==,type:str]
kind: ENC[AES256_GCM,data:wdjlKyYU,iv:Wo2LCBGUS0assx9Wji9FNwROao6KvkbnbViROmBcw1k=,tag:CX1suAJ1b7spde/pqM9pfA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MR3qoC5n8Q56O3T75E9caXOA1bQFnmYm,iv:dxwt685ts7OE9rhm9xEE1gG0bPU4rRXqu/wh1PzYMXQ=,tag:wcNlUmHBh9jDEZjbb8YDVQ==,type:str]
    namespace: ENC[AES256_GCM,data:8uCak70tCNXXpglAxg==,iv:3+aWLBdu08vNQlrbgkYDj7UPdHXP38HTTqaR/6nYqEA=,tag:LiHDxvulLZeCe/iIhQTRaQ==,type:str]
type: ENC[AES256_GCM,data:aSfIZ2nr,iv:OZdbZBAFKR9oVLdfANvA0xlanjllKRnLrTyM2ikwKvU=,tag:+hqLor6jfaCRYmjYgmUvSw==,type:str]
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:y8y52mxdDF0+u46KVYweYRQb/bRvOx0dqspEz+vLag==,iv:cfULIGnhZGVeeF/xhtQy3Sp/J6UIJqDKM01MpUbQirg=,tag:9MckVvZyfVqB/xICCES7Qw==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:UEOfiDh+5BFo2XS+w/veBd0dZLIhq3gH18/r0fnY,iv:3poc0N6AKBXRWy0pO82apOcbJ9D6cTvSInonBC1RBXc=,tag:31Ppr6274OD8VMu5OzxBIQ==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:TFX/+4wi4paHXkx+RsxwPZhxp6xhMpUsHD8Ekozk0U2IgSV0,iv:ppRvtTyBFfBNJ2W/SI+xACk4tA00dR76HbOIrbD9F0w=,tag:FE2gHp0k6AUYg17TG9hjXA==,type:str]
sops:
    age:
        - recipient: age1gwusglw4yl7yhmdym58rnyn6qzr29h5rjjgeajd4h6hqx9ny5gpsak0k5j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eFNtRmhXbEdOS1dYVW1W
            Wk15ZTk3ZC9aZE5iQ1dta3FuVGt1UUdoSzJ3CkZzRE9CM0hDNjhoRWZ1RkNJb0N3
            Q2NmWDc0b3RubnRnRFBUWXZicGdJS3cKLS0tIHBsWnpDbEEvb1Y3TE8zMnJGYmVP
            MDNPc3JiUDYvWmhaWXl6YXhkQ2d4SnMKw8WjJokOWVIdxPXfZc1buj8FC5ix5VbR
            b9s/gqHy5M8fwG5gXrv24oPwdVF+Ot7bgoXasOCUXOuU9NvjZEY9Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T21:21:17Z"
    mac: ENC[AES256_GCM,data:sVxocdboXn8R1M55wJsuoLjZW7/bNzie8mjTQpmQ8zhakydhteOA52xlLs3Nd72Ibl5KS6+TPP/ZWrOK5/ZeSpu9kDMPiuWiPR1QtADDSQM8XQ6zEOSgWZU2pgdMaoFO9T3VzJOU8aIS956Ft7c/ja7aOYPqIW2Xyp6qTX2PRmw=,iv:g6yo4v7AafAVrBtmuKsHMdAKxIhUuMrdrNWpxf7dMvo=,tag:LNWlXx6bCdLeWDCVud6qEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
