// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@app/(public)/dev/boom/page`
 * Purpose: Forced-error route for proving the "Send to Cogni" loop on
 *   candidate-a end-to-end. Rendering this page deterministically throws
 *   a server-side error, which falls through to `(public)/error.tsx`,
 *   which in turn renders `<SendToCogniButton />`.
 * Scope: Public, no-auth. Server component (so the throw lands as a
 *   server-render error and Next stamps a `digest` we can join on).
 *   Lives under `dev/` to make its purpose obvious.
 * Invariants:
 *   - DETERMINISTIC_THROW: every request throws — no flakiness around
 *     "did the error happen this time?" while we drive the loop.
 *   - SERVER_SIDE_THROW: throws on the server (not in a useEffect) so
 *     the digest is generated by Next's render-error path.
 * Side-effects: throws on render.
 * Links: work/items/task.0426.send-to-cogni-error-intake-v0.md
 * @public
 */

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

export default function BoomPage() {
  throw new Error(
    "task.0426 forced-error route — used to prove the 'Send to Cogni' loop on candidate-a"
  );
}
