apiVersion: ENC[AES256_GCM,data:kJQ=,iv:OLA1e4swy0IYFRjtqrQKmb4ycyTrj5qaJkjRfnpj/js=,tag:iYzO5oxtku2d3ANGct4a/A==,type:str]
kind: ENC[AES256_GCM,data:Fb0YrFHU,iv:mNz/HjCFDih4QxlhJyeHXodlxccuSfni3R3psemnX9w=,tag:BjxcdIlkLfxQjCS8UXwcbw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:TqTD1NCzLGq550LJ8f+Z47Mns3dMUSV4,iv:sT8yc68qIwnyGsBg2qBcQ+WF+Jysi5ZbJxsfJJrjjU8=,tag:WTFXEu4BClxunOgU9Mdb/w==,type:str]
  namespace: ENC[AES256_GCM,data:CmURgqOCSd0s7J5s9Q==,iv:f9iJkL+fDJbIWtr3jX0Bis0LqGxM3rasNIH329ObLu0=,tag:SmpLKUZPavKtMhD+iK+qlQ==,type:str]
type: ENC[AES256_GCM,data:t0n551Ia,iv:apN7oBs8xW17Hu4atZY5ol/uNyLfB9wjd2n3ihWeVd8=,tag:Zp5H8eA66EDEVM8iElmp0g==,type:str]
stringData:
  OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:GVwhHiEBKwSVj1+qVCyHrvY+GmPU28fia8RrlN+IJXPddRXwc1GXVWmn7jk=,iv:XBiU6ER+lSqlJBmTVmvr1g3XzSIWAN5y9fUNqTD+148=,tag:iBhMsLcxGy8Vcg2vZzVGew==,type:str]
  GITHUB_TOKEN: ENC[AES256_GCM,data:ctfUsgA2hx2ek42+4ISvcW4cRBxxQzO+ZHwEstNWJBNSpXYi00z47wtXeGZcA/TTjiwGK97VBV2T8huvyFmT4dFartTQohKMRXGgLHEqWg4QyXQ3YrMwg8nxp9CJ,iv:CxOwlngM/emI5MM/Xs06a288zcBlAtuv7FLYZou1Ghs=,tag:EqVjcDoGna9oj3m8MJ5lsA==,type:str]
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:iGXr9XIg087dJU1TE72qhLZcCngASudbESuRXXSmepsloWtSb5KJ4xEU8xnbhVTMlHVpsFfr70KK,iv:i/qHVISb3ojTHQZxcomO2kSKq9sjLGr2/6+sYNPUYUY=,tag:nT9oqsbzmaRGqIzkhixIiA==,type:str]
sops:
  age:
    - recipient: age1nza5xp3rxzyzxp26g4408mpm7pqtmsymcclcsrwt5e7q54y0pffqd3v8d4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPS2t5RkJvaFRaVmVVOGdq
        R0JDMlZmTHRvWm84K0I3OEJ4ZEtCN1daS3pzCkRKaDlxOGFPbWQ3dnkvTTZtenVZ
        UEpFQk52SGYrSjFIeFJEMHpFeEt5bmcKLS0tIEVBNlJ0ZUh6UlVoUWNqeU5HVS9i
        bE9Eb2tibmozN2VhOU41MTJmd0lrU0kK6aM1GvBxJ2Weq9iULHWKNKlzysC7k0ot
        tS1BkFEYkDXHuc9EumkS4Ke3x1Y88oQvi3H5n40N44c7ZyERTuEiPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-25T22:01:24Z"
  mac: ENC[AES256_GCM,data:PMO/8+OZ0GTfL8v//DysHUyMbJRz/Ep36XHYRhKKHMiZHY+qJ7M35Ot8HrMJcyqP3UrxTqcqwyTFNzil//bWqHziUrfolKYNA49t2lKPs2kmVxiodXnbpJkimyi9QC90S0EqYyUANXxS4Rd46wxxzM8U+07LKQzFssv/H+tHeWU=,iv:Lu5D69SXdwZ4RpP9ztfi2jF0SQsIz0OiMCjv9UlrDvE=,tag:JSKr1XaYJT8+hfL0+ltWOA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
