// SPDX-License-Identifier: Polyform-Shield-1.0.0

/**
 * Purpose: Root layout component for Next.js App Router with Geist font configuration and global styles.
 * Scope: Provides HTML structure and font loading for entire application. Does not handle routing or content.
 * Invariants: Renders valid HTML5 structure; applies consistent font variables; includes global CSS.
 * Side-effects: none
 * Notes: Geist fonts loaded with CSS variables for theme consistency.
 * Links: Next.js App Router layout specification
 * @public
 */

import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import type { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): ReactNode {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
