apiVersion: ENC[AES256_GCM,data:XhE=,iv:kaE3MBFPrvWw4s7phqH7bzExUzbrFbubxhFM/WSaxMU=,tag:m0NneRf5Q9tkPczYF80o0g==,type:str]
kind: ENC[AES256_GCM,data:8kk6aQng,iv:r9K9hyCqTumxLZxRWYGHsdV1gQ5faqV1E40AhEVoiYQ=,tag:3YJevNhzCgEU8HRMf3QoRw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:FWBgbM/jhO4Ska4Op164m/V+q3d2oJ/4,iv:QhVHJxkrZYBjJhqdqsWbCesK7LBbiMpQKyktCNfjzaA=,tag:nIrkgpjwWvEV0SVowOD4Ag==,type:str]
  namespace: ENC[AES256_GCM,data:9VsIWCSy1JkBpT5M38/nXQ==,iv:e3rc1yHLo2ybj4XkBV1wfd1/PKasNfvVyfYgd3AdOVY=,tag:4KM6noz+5e+VhqKCfPPg4w==,type:str]
type: ENC[AES256_GCM,data:bOPX0Z4O,iv:WFpEJORe7gyjWCrYZ4UQMEFgkoSD4Y4tcrVr7aeJKdA=,tag:OmxnR5OeeRaEiITjN2J4iw==,type:str]
stringData:
  OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:GJ/UCPA7aIUAl/STA16QZ+BTIm1/XuRM5knZR3lESaT/+4sR71yhVjaXYno=,iv:DwinEfivuWQyLTE25RezX7iM+DPxMTdPujD/n/kaC28=,tag:7nfDMuakJKflPFE5scxdoQ==,type:str]
  GITHUB_TOKEN: ENC[AES256_GCM,data:Ot1pjTYU8lGVDu7SVXJ7L2LJRyBro7fa+zUsqgp7FpmH9TtdPM8/gN0BDrP9bLTpOOhHP8Y1oWzRrTEgAKFDyqbDlEGY1mb2l/KB2C5D+Di6Icb0GNEd4k3Uk7mE,iv:4a8BXkvsp/iMsqhjBzvtxxkmoa4sQUcYWqfTAADlZSI=,tag:Z0I9PPXKM9ymXBejWMbl+w==,type:str]
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:YzoFkLADQ35wDspk0CLmjG74LXvIsll1Y9su1kV9Ui8IwxAi33+WLG0MoafOuZpufOVgOw/xd5LP,iv:RQdwn/aeR+UHSD4mFJtywbimvKBfJBZIW9FN0SMVW6w=,tag:+uY9kEYqqktNaJiRMr0HjA==,type:str]
sops:
  age:
    - recipient: age12gpkglysp68f6vvurq7dxnhjr2zlrvqmer50g853q2hwvfyrzeyqflgcza
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYXZ1WS9WeTFjVnowRlA3
        NCtOT3NCNFc4SHUwU3UwTllUcC9NT1FqaWw0CllFdHVNejFranBzWmhCNG5PMUZh
        VjJRNm9EUlNYd0EzaDFaVUhVRXNKdFkKLS0tIFh0RHdEQW9rbFlQcHMwT3lPUnJj
        aFZnYlJsVjA2NXBFY3lQRWJuckFNczgKLYN3+kSjL+rJr6TBBbcLCUpxnELZGk0i
        e4HphOXW7RHWoaz/e6ayplUaOjXEZS43B+neViRD5yAODuC5bzVnBA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-25T22:01:24Z"
  mac: ENC[AES256_GCM,data:Dq4RTi0sjpmpQkG6rekLpC0Eje2vnwG3itJx73UESjz8T6/M/EVWz8I8YRqXu4CieAG+L+sZJ0aInau/NH9Ze0BKY4TUuzad9bZn4uiAlb0YBomQWFkTexpS2KP3ARmADKtC87fDgI8eiDEwKC1CrXMsXLuAeQcT/ciHllj9hzg=,iv:Xwi75CzwYQnHnPJVrOyUliQXWxmjUvJfhxHlCTtQ/qE=,tag:coOBrNC4BCglEsBgr1djPQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
