apiVersion: ENC[AES256_GCM,data:8Ug=,iv:zefyTuewnOOd2LYY8ON3eWGO5zfIjoFvFtFV2L/45P8=,tag:3TM43Sm3+VhGNTrlmHIpbg==,type:str]
kind: ENC[AES256_GCM,data:fpDxrFkj,iv:mGq6HQbu2KEibQJi8asw9j6xYMtrp8H0OYwBiAmpjz0=,tag:JOtiH2r36RhAWiGzplPOUg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IwVkyRv0foNWHp1SANTOyPrMuHTlLJTR,iv:rry0pUDiyPRqth9+cAzAtmFimzxgSVyBl9EbEZq0zsk=,tag:0th+gvspDTNWX8s53wLtuQ==,type:str]
    namespace: ENC[AES256_GCM,data:Pj5B82bN2P87GiJxeARo3g==,iv:JVwaP63kTgpGGvEQELGg+yqBqhRQU86WIEqNnHFvvoA=,tag:VpYW/vrs5ifh/hKAICbbRg==,type:str]
type: ENC[AES256_GCM,data:WS2oLh0N,iv:dsrXoJqCqcVMrav4T3/enxsifrK7kiWqVJtAKJSJNdM=,tag:8IB5d/OGtiqlNX3p99cGbg==,type:str]
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:81CPSzV2JSgv/7CJNQ2ABH4upOniDhXE7o97CaTen1B3Rg==,iv:a0X1eWY7LikwV6KxIHwvRWE2A4LUBdvFQHIFrdcBb0c=,tag:Tj7abGEJ2mIvaLJ//L0G1g==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:o23WlkLMAZJ9xtQ8BI+jJDf/ObHkCCqPnDDyX/tbRrbw,iv:EnLVpFZNpApUqkYAHm7VfQT6Ls3Wzk06e6EBN4RhUvg=,tag:+t3O4Xrt2L/r6PC1Y/tjfA==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:k2Rp8yCHXK2O7cOPbB3ZBdrNoYL520dC0Kh0PCKletXfrsUKKihF,iv:KtwCUIuCHpg5hPS9hFpZhw2grnnYrq3BDIT+xFTLJPE=,tag:vpaumti+1Asq0ZGkUSWweQ==,type:str]
sops:
    age:
        - recipient: age1z4ew2l0pyw4j59xvml95fyee56zgy94x36nerfeu505e56y083asx6ynlf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTXlzbVNUVUlpa3JWVFFS
            QVVsZ01veVM3Zy9DZVpRakFtU2UzYjFBdlVFClR5eUVFNG5sM3MyWG9yWDBGUldp
            QitTK01UNHNYV2dQK1k5VHB5eUpMbGcKLS0tIHVyS21LTEtFUkRJdXdSVTJEaTFL
            RUdmdFQ1Mldxa2V6bjFVNG00WXNNWlkKL+w6i4dmtWPkEYzNLBRDPAXooqlpLmSE
            wFPRDkPH2QSRLGDhhQNgA0nOqYL7d+v7amZo7n1a7tke7gD+ILBuHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T21:21:17Z"
    mac: ENC[AES256_GCM,data:nFmRCVVnXrLDyDWuXCCbY4H7PTW7Mf0N7S0X2vNMDAm6Fyw0hrICcitetCJc0xy05GZu0tFQCyyVfbdHtkptHUqamzJqmD2nEDHdMcaEBfk6B87sRjaU59l/9+NDVHURCD2AfreX1YW76cL7OZc184EbbbHrAW0QEqkrFpS1HGU=,iv:VRwNzFpSTcmTV0olEGCEyrkc28RnJOuQPwGMp5f8mvE=,tag:n9NyrsRPWXf1YHuBr14Dpg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
