# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cogni-staging

resources:
  - ../../../base/node-app

namePrefix: poly-

images:
  - name: ghcr.io/cogni-dao/cogni-template
    newName: ghcr.io/cogni-dao/cogni-template
    newTag: "staging-placeholder-poly"
  - name: ghcr.io/cogni-dao/cogni-template:placeholder-migrate
    newName: ghcr.io/cogni-dao/cogni-template
    newTag: "staging-placeholder-poly-migrate"

patches:
  - target:
      kind: ConfigMap
      name: node-app-config
    patch: |
      - op: replace
        path: /data/APP_ENV
        value: "preview"
      - op: replace
        path: /data/NODE_NAME
        value: "poly"
      - op: replace
        path: /data/TEMPORAL_NAMESPACE
        value: "cogni-preview"
  - target:
      kind: Service
      name: node-app
    patch: |
      - op: add
        path: /spec/ports/0/nodePort
        value: 30100
