apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cogni-preview

resources:
  - ../../../base/sandbox-openclaw

images:
  - name: ghcr.io/cogni-dao/cogni-sandbox-openclaw
    newTag: "staging-placeholder-sandbox-openclaw"
