# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cogni-candidate-a

resources:
  - ../../../base/scheduler-worker
  - env-state.yaml

images:
  - name: ghcr.io/cogni-dao/cogni-template
    newName: ghcr.io/cogni-dao/cogni-template
    digest: "sha256:c8fa27bc2f8b8e57359fc5fd86f0f02429ed4d707fbfb4e1623ca1cac7375f15"

patches:
  - target:
      kind: ConfigMap
      name: scheduler-worker-config
    patch: |
      - op: replace
        path: /data/TEMPORAL_NAMESPACE
        value: "cogni-candidate-a"
      - op: replace
        path: /data/IMAGE_DIGEST
        value: "candidate-a-placeholder-scheduler-worker"

replacements:
  - source:
      kind: ConfigMap
      name: env-state
      fieldPath: data.VM_IP
    targets:
      - select:
          kind: EndpointSlice
          name: temporal-1
        fieldPaths:
          - endpoints.0.addresses.0
      - select:
          kind: EndpointSlice
          name: postgres-1
        fieldPaths:
          - endpoints.0.addresses.0
      - select:
          kind: EndpointSlice
          name: app-1
        fieldPaths:
          - endpoints.0.addresses.0
      - select:
          kind: EndpointSlice
          name: poly-app-1
        fieldPaths:
          - endpoints.0.addresses.0
      - select:
          kind: EndpointSlice
          name: resy-app-1
        fieldPaths:
          - endpoints.0.addresses.0
