// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@cogni/ai-tools`
 * Purpose: Barrel export for pure tool definitions and contracts.
 * Scope: Re-exports all public types from submodules. Does NOT import @langchain.
 * Invariants: SINGLE_SOURCE_OF_TRUTH - these are the canonical tool definitions.
 * Side-effects: none
 * Links: LANGGRAPH_AI.md, TOOL_USE_SPEC.md
 * @public
 */

export type {
  AuthCapability,
  CheckInfo,
  CiStatusResult,
  ClockCapability,
  CreateBranchResult,
  CreatePrResult,
  DispatchCandidateFlightResult,
  KnowledgeCapability,
  KnowledgeEntry,
  KnowledgeListParams,
  KnowledgeSearchParams,
  KnowledgeWriteParams,
  MergeResult,
  MetricDataPoint,
  MetricQueryResult,
  MetricSummary,
  MetricsCapability,
  MetricTemplate,
  MetricWindow,
  PolyDataActivityOutput,
  PolyDataActivityType,
  PolyDataCapability,
  PolyDataHoldersOutput,
  PolyDataMarketTradesOutput,
  PolyDataPositionsOutput,
  PolyDataResolveUsernameOutput,
  PolyDataTradedEventsOutput,
  PolyDataValueOutput,
  PrSummary,
  RepoCapability,
  RepoListParams,
  RepoListResult,
  RepoOpenParams,
  RepoOpenResult,
  RepoSearchHit,
  RepoSearchParams,
  RepoSearchResult,
  ScheduleCapability,
  ScheduleCreateParams,
  ScheduleInfo,
  ScheduleUpdateParams,
  TemplateQueryParams,
  ToolCapabilities,
  VcsCapability,
  WebSearchCapability,
  WebSearchParams,
  WebSearchResult,
  // Note: WebSearchResultItem exported from tools/web-search to avoid duplicate
  WebSearchTopic,
  WorkItemAssignee,
  WorkItemCapability,
  WorkItemInfo,
  WorkItemQueryParams,
  WorkItemTransitionResult,
} from "./capabilities";
// Capabilities
export {
  CONFIDENCE,
  createFixedClock,
  makeRepoCitation,
  REPO_CITATION_REGEX,
  stubAuthCapability,
  systemClock,
} from "./capabilities";
// Tool catalog
export {
  type CatalogBoundTool,
  createToolCatalog,
  getToolById,
  getToolIds,
  hasToolId,
  TOOL_CATALOG,
  type ToolCatalog,
} from "./catalog";
// Runtime adapter
export { contractToRuntime, toBoundToolRuntime } from "./runtime-adapter";
// Schema compilation
export {
  type ToToolSpecResult,
  type ToToolSpecsResult,
  toToolSpec,
  toToolSpecs,
} from "./schema";
// Tools
export {
  GET_CURRENT_TIME_NAME,
  type GetCurrentTimeInput,
  GetCurrentTimeInputSchema,
  type GetCurrentTimeOutput,
  GetCurrentTimeOutputSchema,
  type GetCurrentTimeRedacted,
  getCurrentTimeBoundTool,
  getCurrentTimeContract,
  getCurrentTimeImplementation,
} from "./tools/get-current-time";
export {
  createKnowledgeReadImplementation,
  KNOWLEDGE_READ_NAME,
  type KnowledgeReadDeps,
  type KnowledgeReadInput,
  KnowledgeReadInputSchema,
  type KnowledgeReadOutput,
  KnowledgeReadOutputSchema,
  type KnowledgeReadRedacted,
  knowledgeReadBoundTool,
  knowledgeReadContract,
  knowledgeReadStubImplementation,
} from "./tools/knowledge-read";
export {
  createKnowledgeSearchImplementation,
  KNOWLEDGE_SEARCH_NAME,
  type KnowledgeSearchDeps,
  type KnowledgeSearchInput,
  KnowledgeSearchInputSchema,
  type KnowledgeSearchOutput,
  KnowledgeSearchOutputSchema,
  type KnowledgeSearchRedacted,
  knowledgeSearchBoundTool,
  knowledgeSearchContract,
  knowledgeSearchStubImplementation,
} from "./tools/knowledge-search";
export {
  createKnowledgeWriteImplementation,
  KNOWLEDGE_WRITE_NAME,
  type KnowledgeWriteDeps,
  type KnowledgeWriteInput,
  KnowledgeWriteInputSchema,
  type KnowledgeWriteOutput,
  KnowledgeWriteOutputSchema,
  type KnowledgeWriteRedacted,
  knowledgeWriteBoundTool,
  knowledgeWriteContract,
  knowledgeWriteStubImplementation,
} from "./tools/knowledge-write";
export {
  createMarketListImplementation,
  MARKET_LIST_NAME,
  type MarketCapability,
  type MarketItem,
  MarketItemSchema,
  type MarketListDeps,
  type MarketListInput,
  MarketListInputSchema,
  type MarketListOutput,
  MarketListOutputSchema,
  type MarketListRedacted,
  marketListBoundTool,
  marketListContract,
  marketListStubImplementation,
} from "./tools/market-list";
export {
  createMetricsQueryImplementation,
  METRICS_QUERY_NAME,
  type MetricsDataPoint,
  MetricsDataPointSchema,
  type MetricsQueryDeps,
  type MetricsQueryInput,
  MetricsQueryInputSchema,
  type MetricsQueryOutput,
  MetricsQueryOutputSchema,
  type MetricsQueryRedacted,
  type MetricsSummary,
  MetricsSummarySchema,
  metricsQueryBoundTool,
  metricsQueryContract,
  metricsQueryStubImplementation,
} from "./tools/metrics-query";
export {
  createPolyCancelOrderImplementation,
  POLY_CANCEL_ORDER_NAME,
  type PolyCancelOrderDeps,
  type PolyCancelOrderInput,
  PolyCancelOrderInputSchema,
  type PolyCancelOrderOutput,
  PolyCancelOrderOutputSchema,
  type PolyCancelOrderRedacted,
  polyCancelOrderBoundTool,
  polyCancelOrderContract,
  polyCancelOrderStubImplementation,
} from "./tools/poly-cancel-order";
export {
  createPolyClosePositionImplementation,
  POLY_CLOSE_POSITION_NAME,
  type PolyClosePositionDeps,
  type PolyClosePositionInput,
  PolyClosePositionInputSchema,
  type PolyClosePositionOutput,
  PolyClosePositionOutputSchema,
  type PolyClosePositionRedacted,
  polyClosePositionBoundTool,
  polyClosePositionContract,
  polyClosePositionStubImplementation,
} from "./tools/poly-close-position";
export {
  createPolyDataActivityImplementation,
  POLY_DATA_ACTIVITY_NAME,
  type PolyDataActivityDeps,
  type PolyDataActivityInput,
  PolyDataActivityInputSchema,
  PolyDataActivityOutputSchema,
  type PolyDataActivityRedacted,
  PolyDataActivityTypeSchema,
  polyDataActivityBoundTool,
  polyDataActivityContract,
  polyDataActivityStubImplementation,
} from "./tools/poly-data-activity";
export {
  POLY_DATA_HELP_NAME,
  type PolyDataHelpInput,
  PolyDataHelpInputSchema,
  type PolyDataHelpOutput,
  PolyDataHelpOutputSchema,
  type PolyDataHelpRedacted,
  polyDataHelpBoundTool,
  polyDataHelpContract,
  polyDataHelpImplementation,
} from "./tools/poly-data-help";
export {
  createPolyDataHoldersImplementation,
  POLY_DATA_HOLDERS_NAME,
  type PolyDataHoldersDeps,
  type PolyDataHoldersInput,
  PolyDataHoldersInputSchema,
  PolyDataHoldersOutputSchema,
  type PolyDataHoldersRedacted,
  polyDataHoldersBoundTool,
  polyDataHoldersContract,
  polyDataHoldersStubImplementation,
} from "./tools/poly-data-holders";
export {
  createPolyDataPositionsImplementation,
  POLY_DATA_POSITIONS_NAME,
  type PolyDataPositionsDeps,
  type PolyDataPositionsInput,
  PolyDataPositionsInputSchema,
  PolyDataPositionsOutputSchema,
  type PolyDataPositionsRedacted,
  polyDataPositionsBoundTool,
  polyDataPositionsContract,
  polyDataPositionsStubImplementation,
} from "./tools/poly-data-positions";
export {
  createPolyDataResolveUsernameImplementation,
  POLY_DATA_RESOLVE_USERNAME_NAME,
  type PolyDataResolveUsernameDeps,
  type PolyDataResolveUsernameInput,
  PolyDataResolveUsernameInputSchema,
  PolyDataResolveUsernameOutputSchema,
  type PolyDataResolveUsernameRedacted,
  polyDataResolveUsernameBoundTool,
  polyDataResolveUsernameContract,
  polyDataResolveUsernameStubImplementation,
} from "./tools/poly-data-resolve-username";
export {
  createPolyDataTradedEventsImplementation,
  POLY_DATA_TRADED_EVENTS_NAME,
  type PolyDataTradedEventsDeps,
  type PolyDataTradedEventsInput,
  PolyDataTradedEventsInputSchema,
  PolyDataTradedEventsOutputSchema,
  type PolyDataTradedEventsRedacted,
  polyDataTradedEventsBoundTool,
  polyDataTradedEventsContract,
  polyDataTradedEventsStubImplementation,
} from "./tools/poly-data-traded-events";
export {
  createPolyDataTradesMarketImplementation,
  POLY_DATA_TRADES_MARKET_NAME,
  type PolyDataTradesMarketDeps,
  type PolyDataTradesMarketInput,
  PolyDataTradesMarketInputSchema,
  PolyDataTradesMarketOutputSchema,
  type PolyDataTradesMarketRedacted,
  polyDataTradesMarketBoundTool,
  polyDataTradesMarketContract,
  polyDataTradesMarketStubImplementation,
} from "./tools/poly-data-trades-market";
export {
  createPolyDataValueImplementation,
  POLY_DATA_VALUE_NAME,
  type PolyDataValueDeps,
  type PolyDataValueInput,
  PolyDataValueInputSchema,
  PolyDataValueOutputSchema,
  type PolyDataValueRedacted,
  polyDataValueBoundTool,
  polyDataValueContract,
  polyDataValueStubImplementation,
} from "./tools/poly-data-value";
export {
  createPolyListOrdersImplementation,
  POLY_LIST_ORDERS_NAME,
  type PolyListOrdersDeps,
  type PolyListOrdersInput,
  PolyListOrdersInputSchema,
  type PolyListOrdersOutput,
  PolyListOrdersOutputSchema,
  type PolyListOrdersRedacted,
  polyListOrdersBoundTool,
  polyListOrdersContract,
  polyListOrdersStubImplementation,
} from "./tools/poly-list-orders";
export {
  createPolyPlaceTradeImplementation,
  POLY_PLACE_TRADE_NAME,
  type PolyClosePositionRequest,
  type PolyListOpenOrdersRequest,
  type PolyOpenOrder,
  type PolyPlaceTradeDeps,
  type PolyPlaceTradeInput,
  PolyPlaceTradeInputSchema,
  type PolyPlaceTradeOutput,
  PolyPlaceTradeOutputSchema,
  type PolyPlaceTradeReceipt,
  type PolyPlaceTradeRedacted,
  type PolyPlaceTradeRequest,
  type PolyTradeCapability,
  polyPlaceTradeBoundTool,
  polyPlaceTradeContract,
  polyPlaceTradeStubImplementation,
} from "./tools/poly-place-trade";
export {
  createRepoListImplementation,
  REPO_LIST_NAME,
  type RepoListDeps,
  type RepoListInput,
  RepoListInputSchema,
  type RepoListOutput,
  RepoListOutputSchema,
  type RepoListRedacted,
  repoListBoundTool,
  repoListContract,
  repoListStubImplementation,
} from "./tools/repo-list";
export {
  createRepoOpenImplementation,
  REPO_OPEN_NAME,
  type RepoOpenDeps,
  type RepoOpenInput,
  RepoOpenInputSchema,
  type RepoOpenOutput,
  RepoOpenOutputSchema,
  type RepoOpenRedacted,
  repoOpenBoundTool,
  repoOpenContract,
  repoOpenStubImplementation,
} from "./tools/repo-open";
export {
  createRepoSearchImplementation,
  REPO_SEARCH_NAME,
  type RepoSearchDeps,
  type RepoSearchHitOutput,
  RepoSearchHitSchema,
  type RepoSearchInput,
  RepoSearchInputSchema,
  type RepoSearchOutput,
  RepoSearchOutputSchema,
  type RepoSearchRedacted,
  repoSearchBoundTool,
  repoSearchContract,
  repoSearchStubImplementation,
} from "./tools/repo-search";
export {
  createScheduleListImplementation,
  SCHEDULE_LIST_NAME,
  type ScheduleListDeps,
  type ScheduleListInput,
  ScheduleListInputSchema,
  type ScheduleListOutput,
  ScheduleListOutputSchema,
  type ScheduleListRedacted,
  scheduleListBoundTool,
  scheduleListContract,
  scheduleListStubImplementation,
} from "./tools/schedule-list";
export {
  createScheduleManageImplementation,
  SCHEDULE_MANAGE_NAME,
  type ScheduleManageDeps,
  type ScheduleManageInput,
  ScheduleManageInputSchema,
  type ScheduleManageOutput,
  ScheduleManageOutputSchema,
  type ScheduleManageRedacted,
  scheduleManageBoundTool,
  scheduleManageContract,
  scheduleManageStubImplementation,
} from "./tools/schedule-manage";
export {
  createVcsCreateBranchImplementation,
  VCS_CREATE_BRANCH_NAME,
  type VcsCreateBranchDeps,
  type VcsCreateBranchInput,
  VcsCreateBranchInputSchema,
  type VcsCreateBranchOutput,
  VcsCreateBranchOutputSchema,
  type VcsCreateBranchRedacted,
  vcsCreateBranchBoundTool,
  vcsCreateBranchContract,
  vcsCreateBranchStubImplementation,
} from "./tools/vcs-create-branch";
export {
  createVcsFlightCandidateImplementation,
  VCS_FLIGHT_CANDIDATE_NAME,
  type VcsFlightCandidateDeps,
  type VcsFlightCandidateInput,
  VcsFlightCandidateInputSchema,
  type VcsFlightCandidateOutput,
  VcsFlightCandidateOutputSchema,
  type VcsFlightCandidateRedacted,
  vcsFlightCandidateBoundTool,
  vcsFlightCandidateContract,
  vcsFlightCandidateStubImplementation,
} from "./tools/vcs-flight-candidate";
export {
  createVcsGetCiStatusImplementation,
  VCS_GET_CI_STATUS_NAME,
  type VcsGetCiStatusDeps,
  type VcsGetCiStatusInput,
  VcsGetCiStatusInputSchema,
  type VcsGetCiStatusOutput,
  VcsGetCiStatusOutputSchema,
  type VcsGetCiStatusRedacted,
  vcsGetCiStatusBoundTool,
  vcsGetCiStatusContract,
  vcsGetCiStatusStubImplementation,
} from "./tools/vcs-get-ci-status";
export {
  createVcsListPrsImplementation,
  VCS_LIST_PRS_NAME,
  type VcsListPrsDeps,
  type VcsListPrsInput,
  VcsListPrsInputSchema,
  type VcsListPrsOutput,
  VcsListPrsOutputSchema,
  type VcsListPrsRedacted,
  vcsListPrsBoundTool,
  vcsListPrsContract,
  vcsListPrsStubImplementation,
} from "./tools/vcs-list-prs";
export {
  createVcsMergePrImplementation,
  VCS_MERGE_PR_NAME,
  type VcsMergePrDeps,
  type VcsMergePrInput,
  VcsMergePrInputSchema,
  type VcsMergePrOutput,
  VcsMergePrOutputSchema,
  type VcsMergePrRedacted,
  vcsMergePrBoundTool,
  vcsMergePrContract,
  vcsMergePrStubImplementation,
} from "./tools/vcs-merge-pr";
export {
  createWalletTopTradersImplementation,
  WALLET_TOP_TRADERS_NAME,
  type WalletCapability,
  type WalletOrderBy,
  WalletOrderBySchema,
  type WalletTimePeriod,
  WalletTimePeriodSchema,
  type WalletTopTraderItem,
  WalletTopTraderItemSchema,
  type WalletTopTradersDeps,
  type WalletTopTradersInput,
  WalletTopTradersInputSchema,
  type WalletTopTradersOutput,
  WalletTopTradersOutputSchema,
  type WalletTopTradersRedacted,
  walletTopTradersBoundTool,
  walletTopTradersContract,
  walletTopTradersStubImplementation,
} from "./tools/wallet-top-traders";
export {
  createWebSearchImplementation,
  WEB_SEARCH_NAME,
  type WebSearchDeps,
  type WebSearchInput,
  WebSearchInputSchema,
  type WebSearchOutput,
  WebSearchOutputSchema,
  type WebSearchRedacted,
  type WebSearchResultItem,
  WebSearchResultItemSchema,
  webSearchBoundTool,
  webSearchContract,
  webSearchStubImplementation,
} from "./tools/web-search";
export {
  createWorkItemQueryImplementation,
  WORK_ITEM_QUERY_NAME,
  type WorkItemQueryDeps,
  type WorkItemQueryInput,
  WorkItemQueryInputSchema,
  type WorkItemQueryOutput,
  WorkItemQueryOutputSchema,
  type WorkItemQueryRedacted,
  workItemQueryBoundTool,
  workItemQueryContract,
  workItemQueryStubImplementation,
} from "./tools/work-item-query";
export {
  createWorkItemTransitionImplementation,
  WORK_ITEM_TRANSITION_NAME,
  type WorkItemTransitionDeps,
  type WorkItemTransitionInput,
  WorkItemTransitionInputSchema,
  type WorkItemTransitionOutput,
  WorkItemTransitionOutputSchema,
  type WorkItemTransitionRedacted,
  workItemTransitionBoundTool,
  workItemTransitionContract,
  workItemTransitionStubImplementation,
} from "./tools/work-item-transition";
// Tool types
export type {
  BoundTool,
  ToolContract,
  ToolErrorCode,
  ToolImplementation,
  ToolResult,
} from "./types";
